# Generated by Django 3.1.4 on 2020-12-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0004_auto_20201223_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employment',
            field=models.CharField(default='', max_length=255, verbose_name='Employment'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='', max_length=3, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='user',
            name='site',
            field=models.URLField(default='', verbose_name='Web-site'),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, help_text='Post creation time', verbose_name='Created'),
        ),
    ]
