# Generated by Django 3.1.4 on 2020-12-23 13:44

from django.db import migrations, models
import socialnetwork.models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0005_auto_20201223_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, storage='C:\\Users\\egorw\\PycharmProjects\\avatrade\\avasocial\\data', upload_to='', verbose_name='Avatar picture'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=255, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employment',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Employment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='site',
            field=models.URLField(blank=True, default='', verbose_name='Web-site'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Surname'),
        ),
    ]
