# Generated by Django 3.1.4 on 2020-12-23 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialnetwork', '0007_auto_20201223_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.URLField(blank=True, default='', verbose_name='Web-site')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='Country')),
                ('city', models.CharField(blank=True, default='', max_length=255, verbose_name='City')),
                ('employment', models.CharField(blank=True, default='', max_length=255, verbose_name='Employment')),
                ('avatar', models.FileField(blank=True, storage='C:\\Users\\egorw\\PycharmProjects\\avatrade\\avasocial\\data', upload_to='', verbose_name='Avatar picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.ForeignKey(help_text='User submitted a post', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
