# Generated by Django 3.1.4 on 2020-12-23 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0008_auto_20201223_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'User Profile'},
        ),
    ]
