# Generated by Django 3.1.4 on 2020-12-23 15:49

import django.contrib.auth.models
from django.db import migrations, models
import socialnetwork.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('socialnetwork', '0009_auto_20201223_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtension',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='', max_length=254, validators=[socialnetwork.models.validate_email], verbose_name='E-mail'),
        ),
    ]
