# Generated by Django 3.1.4 on 2020-12-23 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0010_auto_20201223_1749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExtension',
        ),
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.ForeignKey(help_text='User submitted a post', on_delete=django.db.models.deletion.CASCADE, to='socialnetwork.profile', verbose_name='User'),
        ),
    ]
