# Generated by Django 3.1.4 on 2020-12-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0011_auto_20201223_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='profile',
        ),
    ]
