# Generated by Django 3.1.4 on 2020-12-23 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import socialnetwork.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialnetwork', '0014_remove_profile_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Name')),
                ('surname', models.CharField(blank=True, default='', max_length=255, verbose_name='Surname')),
                ('email', models.EmailField(max_length=254, validators=[socialnetwork.models.validate_email], verbose_name='E-mail')),
                ('site', models.URLField(blank=True, default='', verbose_name='Web-site')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='Country')),
                ('city', models.CharField(blank=True, default='', max_length=255, verbose_name='City')),
                ('employment', models.CharField(blank=True, default='', max_length=255, verbose_name='Employment')),
                ('avatar', models.FileField(blank=True, storage='C:\\Users\\egorw\\PycharmProjects\\avatrade\\avasocial\\data', upload_to='', verbose_name='Avatar picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(help_text='User submitted a post', on_delete=django.db.models.deletion.CASCADE, to='socialnetwork.userprofile', verbose_name='User'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
