# Generated by Django 3.1.4 on 2020-12-23 18:51

from django.db import migrations, models
import socialnetwork.models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0015_auto_20201223_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(verbose_name='Status')),
                ('message', models.TextField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(help_text='Required. Personal e-mail address', max_length=254, validators=[socialnetwork.models.validate_email], verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='employment',
            field=models.CharField(blank=True, default='', help_text='Place of work', max_length=255, verbose_name='Employment'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, default='', help_text='First Name', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='site',
            field=models.URLField(blank=True, default='', help_text='Personal Web-page', verbose_name='Web-site'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='surname',
            field=models.CharField(blank=True, default='', help_text='Last Name', max_length=255, verbose_name='Surname'),
        ),
    ]
