# Generated by Django 3.1.4 on 2020-12-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0017_auto_20201223_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes_users',
            field=models.TextField(blank=True, default=''),
        ),
    ]
